// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;


public sealed class CodeDOMCreatedClass
{
    
    // The width of the object.
    private double widthValue;
    
    // The height of the object.
    private double heightValue;
    
    public CodeDOMCreatedClass(double width, double height)
    {
        this.widthValue = width;
        this.heightValue = height;
    }
    
    // The Width property for the object.
    public double Width
    {
        get
        {
            return this.widthValue;
        }
    }
    
    // The Height property for the object.
    public double Height
    {
        get
        {
            return this.heightValue;
        }
    }
    
    // The Area property for the object.
    public double Area
    {
        get
        {
            return (this.widthValue * this.heightValue);
        }
    }
    
    public override string ToString()
    {
        return string.Format("The object:\n width = {0},\n height = {1},\n area = {2}", this.Width, this.Height, this.Area);
    }
    
    public static void Main()
    {
        CodeDOMCreatedClass testClass = new CodeDOMCreatedClass(5.3, 6.9);
        System.Console.WriteLine(testClass.ToString());
    }
}
